module.exports = {
  extends: 'eslint:recommended',
  rules: {
    // eslint:recommended overrides
    'no-console': 0,
    'no-unused-vars': [2, { argsIgnorePattern: '^_', ignoreRestSiblings: true }],

    // Possible Errors
    'for-direction': 2,
    'no-await-in-loop': 0,
    'no-prototype-builtins': 0,
    'no-template-curly-in-string': 2,
    'valid-jsdoc': 0,

    // Best Practices
    'accessor-pairs': 0,
    'array-callback-return': 2,
    'block-scoped-var': 2,
    'class-methods-use-this': 0,
    'complexity': 0,
    'consistent-return': 0,
    'curly': [2, 'multi-line'],
    'default-case': 0,
    'dot-location': [2, 'property'],
    'dot-notation': [2, { allowPattern: '[^a-zA-Z]' }],
    'eqeqeq': [2, 'always', { null: 'ignore' }],
    'guard-for-in': 2,
    'no-alert': 0,
    'no-caller': 2,
    'no-div-regex': 0,
    'no-else-return': 0,
    'no-empty-function': 0,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-floating-decimal': 0,
    'no-implicit-coercion': 0,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 0,
    'no-iterator': 0,
    'no-labels': 0,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new': 0,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 0,
    'no-proto': 0,
    'no-restricted-properties': 0,
    'no-return-assign': 2,
    'no-return-await': 2,
    'no-script-url': 0,
    'no-self-compare': 2,
    'no-sequences': 0,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': 0,
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-useless-return': 2,
    'no-void': 2,
    'no-warning-comments': 0,
    'no-with': 2,
    'prefer-promise-reject-errors': 0,
    'radix': 0,
    'require-await': 0,
    'vars-on-top': 0,
    'wrap-iife': 0,
    'yoda': [2, 'never', { onlyEquality: true }],

    // Stylistic Issues
    'array-bracket-newline': 0,
    'array-bracket-spacing': 2,
    'array-element-newline': 0,
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    'camelcase': 2,
    'capitalized-comments': 0,
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': 2,
    'comma-style': 0,
    'computed-property-spacing': 2,
    'consistent-this': 0,
    'eol-last': 2,
    'func-call-spacing': 2,
    'func-name-matching': 0,
    'func-names': 0,
    'func-style': 0,
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'indent-legacy': [2, 2, { MemberExpression: 1, SwitchCase: 1 }],
    'jsx-quotes': 2,
    'key-spacing': 2,
    'keyword-spacing': 2,
    'line-comment-position': 0,
    'linebreak-style': 2,
    'lines-around-comment': 0,
    'max-depth': 0,
    'max-len': [2, 80, { ignorePattern: '(=|:) require\\(', ignoreRegExpLiterals: true, ignoreTrailingComments: true, ignoreUrls: true }],
    'max-lines': 0,
    'max-nested-callbacks': 0,
    'max-params': 0,
    'max-statements': 0,
    'max-statements-per-line': 0,
    'multiline-ternary': 0,
    'new-cap': 0,
    'new-parens': 0,
    'newline-per-chained-call': 0,
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-operators': 0,
    'no-multi-assign': 0,
    'no-multiple-empty-lines': [2, { max: 1 }],
    'no-negated-condition': 0, // unless we find a good way to enable only for two-branch if-else
    'no-nested-ternary': 0,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-tabs': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'nonblock-statement-body-position': 2,
    'object-curly-newline': 0,
    'object-curly-spacing': [2, 'always'],
    'object-property-newline': 0,
    'one-var': [2, 'never'],
    'one-var-declaration-per-line': 0,
    'operator-assignment': 0,
    'operator-linebreak': 0,
    'padded-blocks': [2, 'never'],
    'padding-line-between-statements': 0,
    'quote-props': 0,
    'quotes': [2, 'single', { avoidEscape: true }],
    'require-jsdoc': 0,
    'semi': 2,
    'semi-spacing': 2,
    'semi-style': 0,
    'sort-keys': 0,
    'sort-vars': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': [2, { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 0,
    'space-unary-ops': [2, { words: true, nonwords: false }],
    'spaced-comment': 2,
    'switch-colon-spacing': 2,
    'template-tag-spacing': 2,
    'unicode-bom': 0,
    'wrap-regex': 0,
  },
};
